@extends('layouts.app')
@section('title', 'Keyword Suggestion')
@section('content')
<div class="page-head">
    <div><h1>Keyword Suggestion</h1><p>AI-generated local SEO keywords to help clients rank on Google.</p></div>
</div>

<div class="card" style="margin-bottom:18px;">
    <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;">
        <label><span class="lbl">Business name</span><input type="text" id="k-business" placeholder="e.g. Bright Smile Dental"></label>
        <label><span class="lbl">City</span><input type="text" id="k-city" placeholder="e.g. Ghaziabad"></label>
        <label><span class="lbl">Industry (optional)</span><input type="text" id="k-industry" placeholder="e.g. Dental clinic"></label>
    </div>
    @if($clients->isNotEmpty())
        <div style="margin-top:12px;font-size:12.5px;color:var(--muted);">
            Quick fill:
            @foreach($clients as $c)
                <button type="button" class="chip" data-name="{{ $c->name }}" data-industry="{{ $c->industry }}" style="border:1px solid var(--line);background:#fcfcfa;border-radius:999px;padding:4px 11px;font-size:12px;cursor:pointer;margin:2px;">{{ $c->name }}</button>
            @endforeach
        </div>
    @endif
    <button class="btn" id="gen-btn" style="margin-top:16px;">✦ Generate keywords</button>
</div>

<div id="results"></div>

@push('scripts')
<script>
const csrf = document.querySelector('meta[name=csrf-token]').content;

// quick-fill chips
document.querySelectorAll('.chip').forEach(chip => {
    chip.addEventListener('click', () => {
        document.getElementById('k-business').value = chip.dataset.name || '';
        document.getElementById('k-industry').value = chip.dataset.industry || '';
    });
});

document.getElementById('gen-btn').addEventListener('click', async () => {
    const business = document.getElementById('k-business').value.trim();
    const city = document.getElementById('k-city').value.trim();
    const industry = document.getElementById('k-industry').value.trim();
    const results = document.getElementById('results');

    if (!business || !city) { alert('Please enter business name and city.'); return; }

    const btn = document.getElementById('gen-btn');
    btn.textContent = 'Generating…'; btn.disabled = true;
    results.innerHTML = '<div class="card"><div style="text-align:center;color:var(--muted);padding:20px;">Thinking of the best keywords…</div></div>';

    try {
        const res = await fetch("{{ route('keywords.generate') }}", {
            method: 'POST',
            headers: {'X-CSRF-TOKEN': csrf, 'Content-Type': 'application/json'},
            body: JSON.stringify({business, city, industry})
        });
        const data = await res.json();
        if(res.status === 402 && window.handlePlanRequired(data)) return;
        if(data.error){ results.innerHTML = '<div class="alert error">' + data.error + '</div>'; return; }
        renderGroups(data.groups || [], data.source);
    } catch (e) {
        results.innerHTML = '<div class="alert error">Could not generate. Try again.</div>';
    } finally {
        btn.textContent = '✦ Generate keywords'; btn.disabled = false;
    }
});

function renderGroups(groups, source){
    const results = document.getElementById('results');
    if (!groups.length){ results.innerHTML = '<div class="alert info">No keywords returned.</div>'; return; }

    let banner = '';
    if (source === 'ai') {
        banner = '<div style="background:var(--teal-soft);border:1px solid #cfe6e0;border-radius:10px;padding:9px 14px;margin-bottom:14px;font-size:12.5px;color:var(--teal-ink);">✨ AI-generated by Gemini</div>';
    } else {
        banner = '<div style="background:var(--amber-soft);border:1px solid #f0d9a8;border-radius:10px;padding:9px 14px;margin-bottom:14px;font-size:12.5px;color:#8a5a08;">⚡ Template keywords (AI limit reached — wait ~30s and try once more for AI results)</div>';
    }

    let html = banner + '<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;">';
    groups.forEach(g => {
        html += '<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;">'
            + '<strong>' + escapeHtml(g.group || 'Keywords') + '</strong>'
            + '<button class="copy-btn btn btn-ghost" style="padding:5px 10px;font-size:11.5px;">Copy all</button></div>'
            + '<div style="display:flex;flex-wrap:wrap;gap:7px;">';
        (g.keywords || []).forEach(k => {
            html += '<span style="background:var(--teal-soft);color:var(--teal-ink);border-radius:8px;padding:5px 10px;font-size:12.5px;">' + escapeHtml(k) + '</span>';
        });
        html += '</div></div>';
    });
    html += '</div>';
    results.innerHTML = html;

    // wire copy buttons
    document.querySelectorAll('.copy-btn').forEach((btn, i) => {
        btn.addEventListener('click', () => {
            const kws = (groups[i].keywords || []).join('\n');
            navigator.clipboard.writeText(kws);
            btn.textContent = 'Copied!';
            setTimeout(() => btn.textContent = 'Copy all', 1500);
        });
    });
}

function escapeHtml(s){
    return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
</script>
@endpush
@endsection
